# Generated by Django 4.1 on 2022-10-26 21:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppGR', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
            ],
        ),
    ]
